model:
  ####### NBody #######
  # module: csmpn.models.models.EGNN
  # task_type: mse_regression

  # module: csmpn.models.models.CLGNN
  # task_type: mse_regression



  # module: csmpn.models.models.SimplicialMPNN
  # task_type: mse_regression

  # module: csmpn.models.models.CliffordSimplicialMPNN
  # task_type: mse_regression

  # module: csmpn.models.models.CliffordSharedSimplicialMPNN
  # task_type: mse_regression


  ###### Motion #######
  # module: csmpn.models.models.MotionCLGNN
  # task_type: mse_regression

  # module: csmpn.models.models.EGNN_motion
  # task_type: mse_regression

  # module: csmpn.models.models.CliffordSharedSimplicialMPNN_motion
  # task_type: mse_regression

  # module: csmpn.models.models.EMPSN_motion
  # task_type: mse_regression
  

  
  ####### MD17 #######
  # module: csmpn.models.models.EGNN_md17
  # task_type: mse_regression

  # module: csmpn.models.models.MD17CLGNN
  # task_type: mse_regression

  module: csmpn.models.models.CliffordSharedSimplicialMPNN_md17
  task_type: mse_regression

  # module: csmpn.models.models.EMPSN_md17
  # task_type: mse_regression
  
  # module: csmpn.models.models.MPNN_md17
  # task_type: mse_regression


  ###### GWL ######
  # module: csmpn.models.models.CliffordSharedSimplicialMPNN_GWL
  # task_type: GEO

  # module: csmpn.models.models.SharedSimplicialMPNN_GWL
  # task_type: GWL

  # module: csmpn.models.models.CLGNN_GWL
  # task_type: GEO

  # module: csmpn.models.models.MPNN_GWL