program: csmpn/hulls.py

command:
  - ${env}
  - ${interpreter} 
  - ${program} 
  - --trainer.module=engineer.Trainer
  - --trainer.val_check_interval=1024
  - --trainer.max_steps=131072
  - --dataset.module=csmpn.data.hulls.ConvexHullDataset
  - --optimizer.module=torch.optim.Adam
  - ${args}

parameters:
  _model_simplicial:
    values:
      [
        "'--model.module=csmpn.models.hulls_cssmpnn.HullsCliffordSharedSimplicialMPNN --dataset.simplicial=True'",
      ]
  dataset.batch_size:
    values: [16]
  optimizer.lr:
    values: [0.001]

