program: csmpn/md17.py

command:
  - ${env}
  - ${interpreter} 
  - ${program} 
  - -C csmpn/configs/engineer/trainer.yaml
  - -C csmpn/configs/optimizer/adam.yaml
  - --dataset.module=csmpn.data.md17.MD17Dataset
  - --model.module=csmpn.models.md17_cssmpnn.CliffordSharedSimplicialMPNN_md17
  - --trainer.val_check_interval=128
  - --trainer.max_steps=150000 
  - ${args}

parameters:
  _model_simplicial:
    values:
      [
        "'--model.module=csmpn.models.md17_cssmpnn.CliffordSharedSimplicialMPNN_md17 --dataset.simplicial=True'",
      ]
  _dataset.molecule_type_dis:
    values:
      [
        --dataset.molecule_type='aspirin' --dataset.dis=3,
        --dataset.molecule_type='benzene2017' --dataset.dis=10000,
        --dataset.molecule_type='ethanol' --dataset.dis=10000,
        --dataset.molecule_type='malonaldehyde' --dataset.dis=10000,
      ]
  dataset.batch_size:
    values: [100]
  model.num_layers:
    values: [5]
  model.num_hidden:
    values: [32]
  optimizer.lr:
    values: [3.e-3]
  optimizer.weight_decay:
    values: [1.e-6]
