project: clifford-simplicial
entity: badboyz2000
program: csmpn/motion.py

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --dataset.module=csmpn.data.motion.MotionDataset
  - -C csmpn/configs/engineer/trainer.yaml
  - -C csmpn/configs/optimizer/adam.yaml
  --model.module=csmpn.models.motion_cssmpnn.MotionCliffordSharedSimplicialMPNN
  - --trainer.val_check_interval=128
  - --trainer.max_steps=10000
  - ${args}

parameters:
  _model_simplicial:
    values:
      [
        "'--model.module=csmpn.models.motion_cssmpnn.MotionCliffordSharedSimplicialMPNN --dataset.simplicial=True'",
      ]
  dataset.num_training_samples:
    values: [200]
  model.num_layers:
    values: [4]
  model.num_hidden:
    values: [28]
  optimizer.lr:
    values: [5.e-4]
  optimizer.weight_decay:
    values: [1.e-4]