project: clifford-simplicial
entity: badboyz2000
program: csmpn/nba.py

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - -C csmpn/configs/engineer/trainer.yaml
  - -C csmpn/configs/optimizer/adam.yaml
  - --dataset.module=csmpn.data.nba.NBADataset
  - --trainer.val_check_interval=128
  - --trainer.max_steps=10000
  - ${args}
parameters:
  _model_simplicial:
    values:
      [
        "'--model.module=csmpn.models.nba_cssmpnn.NBACliffordSharedSimplicialMPNN --dataset.simplicial=True'",
      ]
  dataset.dis:
    values: [10000]
  dataset.mode:
    values: ['atk', 'def']
  model.num_layers:
    values: [3]
  model.num_hidden:
    values: [40]
  optimizer.lr:
    values: [5.e-3]
