dataset:
  # module: csmpn.data.data.NBody  
  # simplicial: True

  # module: csmpn.data.data.QM9Dataset
  # simplicial: False
  # name: mu

  # module: csmpn.data.data.MotionDataset

  module: csmpn.data.MD17Dataset

  # module: csmpn.data.data.GWLDataset

